---
title: "Análise Exploratória - Malária"
output: html_notebook
---

```{r}
# Pacotes transformação de dados
install.packages(c("tidyverse", "lubridate"))

# Pacotes plotagem
install.packages(c("geobr","sf","ggplot2","dplyr"))
install.packages("moments")
install.packages(c("skimr"))

library(moments)
library(tidyverse)
library(lubridate)
library(geobr)
library(sf)
library(ggplot2)
library(dplyr)
library(scales)
library(skimr)
```

```{r}
# Carregamento de dts
load("malaria_2016.RData")
malaria_2016 <- data

load("malaria_2017.RData")
malaria_2017 <- data

load("malaria_2018.RData")
malaria_2018 <- data

load("malaria_2019.RData")
malaria_2019 <- data

ls()
```

```{r}
# Junção de dts
malaria <- bind_rows(
  malaria_2016,
  malaria_2017,
  malaria_2018,
  malaria_2019
)
```

```{r}
# Verificação dos dados
glimpse(malaria)

```


```{r}
str(malaria)
```
```{r}
skim(malaria)
```

```{r}
# Transformação de tipagem de colunas
malaria <- malaria %>%
  mutate(
    notification.month = as.numeric(as.character(notification.month)),
    notification.year = as.numeric(as.character(notification.year)),
    exam.month = as.numeric(as.character(exam.month)),
    exam.year = as.numeric(as.character(exam.year)),
    treatment.month = as.numeric(as.character(treatment.month)),
    treatment.year = as.numeric(as.character(treatment.year)),
    symptom.month = as.numeric(as.character(symptom.month)),
    symptom.year = as.numeric(as.character(symptom.year))
  )
```

```{r}
# Verificação de tipagem alterada
glimpse(malaria)
```
```{r}
# Filtragem para dados dentro do escopo a ser analisado 2016-2019
malaria <- malaria %>%
  filter(notification.year >= 2016 & notification.year <= 2019)
```

```{r}
# Filtragem para dados somente no Brasil
malaria <- malaria %>%
  filter(infection.country == "Brazil")
```


```{r}
# Filtragem de linhas únicas 
malaria <- malaria %>%
  distinct()
```

```{r}
# Criação de coluna data de notificação
malaria <- malaria %>%
  mutate(
    notification.date = as.Date(
      paste(notification.year, notification.month, "01", sep="-")
    )
  )
```

```{r}
# Análise de valores do campo exam.result
unique(malaria$exam.result)
```

```{r}
# Criação de campo malaria.type
malaria <- malaria %>%
  mutate(
    malaria.type = case_when(
      exam.result == "negative" ~ "Negativo",
      exam.result == "vivax" ~ "Vivax",
      exam.result == "falciparum" ~ "Falciparum",
      TRUE ~ "Outros"
    )
  )
```

```{r}
# Cálculo de percentual de positivos no Brasil
total_brasil <- nrow(malaria)


estado_resumo <- malaria %>%
  mutate(
    positive = exam.result != "negative"
  ) %>%
  group_by(notification.state) %>%
  summarise(
    positivos = sum(positive, na.rm = TRUE)
  ) %>%
  mutate(percentual = positivos/total_brasil*100)
```

```{r}
br_states <- read_state()
```
```{r}
estado_resumo <- estado_resumo %>%
  rename(abbrev_state = notification.state)
```

```{r}
mapa <- br_states %>%
  left_join(estado_resumo, by="abbrev_state")
```

```{r}
centros <- sf::st_centroid(mapa)
```


```{r}
# Plotagem de gráfico de mapa do Brasil com a proporção de positivos por estado
ggplot(mapa) +
  geom_sf(aes(fill = percentual)) +
   geom_sf_label(data = centros,
               aes(label = abbrev_state),
               size = 2) +
  scale_fill_viridis_c(option="plasma", na.value="grey90") +
  labs(
    title = "Distribuição espacial da proporção de casos positivos\n de malária no Brasil (2016–2019)",
    fill = "Percentual (%)"
  ) +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```
```{r}
estado_resumo
total_brasil
table(malaria$exam.result)
```
```{r}
unique(malaria$notification.state)
```
```{r}
malaria_exam_binary <- malaria %>%
  mutate(
    exam.binary = ifelse(is.na(exam.result), NA,
                         ifelse(exam.result == "negative", "Negativo", "Positivo"))
  )
```

```{r}
# Variável que armazena o tipo de malária por data de notificação
casos_tempo <- malaria_exam_binary %>%
  group_by(notification.date, exam.binary) %>%
  summarise(
    total = n(),
    .groups = "drop"
  )
```

```{r}
# Plotagem do gráfico de evolução temporal dos tipos de malária
ggplot(casos_tempo,
       aes(x = notification.date,
           y = total,
           color = exam.binary)) +
  geom_line(size = 1) +
  labs(
    title = "Evolução dos casos de malária (2016–2019)",
    x = "Ano",
    y = "Número de exames",
    color = "Resultado"
  ) +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```




```{r}
names(mapa)
```

```{r}
malaria_type_group <- malaria %>%
  filter(exam.result != "negative") %>%
  mutate(
    malaria.type_group = ifelse(exam.result == "falciparum", "Falciparum",
                         ifelse(exam.result == "vivax", "Vivax", "Outros"))
  )
```



```{r}
# Plotagem do gráfico de evolução temporal dos tipos de malária
ggplot(malaria_type_group, aes(x = notification.year, fill = malaria.type_group)) +
  geom_bar() +
  theme_minimal() +
  labs(
    title = "Distribuição dos resultados positivos de exame de malária",
    x = "Ano",
    y = "Número de casos",
    fill = "" 
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
malaria_race <- malaria %>%
group_by(race) %>%
summarize(n = n()) %>%
mutate(
  proportion = n / sum(n),
  label = percent(proportion, accuracy = 0.1),
  )

ggplot(malaria_race, aes(x = "", y = race, fill = race)) +
  geom_col(width=1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5)) +
  theme_minimal() +
  labs(
    title = "Distribuição dos resultados positivos de exame de malária",
    x = "Anos 2016-2019",
    y = "Número de casos",
    fill = "" 
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
  )


```
```{r}
malaria_qty <- malaria

#registros NA
any(is.na(malaria_qty$qty.parasites))
colSums(is.na(malaria_qty))

#Mediadas de Tendencia Central
#media
mean(malaria_qty$qty.parasites, na.rm = TRUE)

#mediana
median(malaria_qty$qty.parasites, na.rm = TRUE)

#moda
moda <- function(malaria_qty) {
  umalaria_qty <- unique(malaria_qty)
  umalaria_qty[which.max(tabulate(match(malaria_qty, umalaria_qty)))]
}

moda(malaria_qty$qty.parasites)

#resumo
summary(malaria_qty$qty.parasites)

#Medidas de Dispersão
#variancia
var(malaria_qty$qty.parasites, na.rm = TRUE)

#desvio padrao
sd(malaria_qty$qty.parasites, na.rm = TRUE)

#amplitude
range(malaria_qty$qty.parasites, na.rm = TRUE)
diff(range(malaria_qty$qty.parasites, na.rm = TRUE))

#intervalo inter quartil
IQR(malaria_qty$qty.parasites, na.rm = TRUE)

#coeficiente de variacao
cv <- sd(malaria_qty$qty.parasites, na.rm=TRUE) /
      mean(malaria_qty$qty.parasites, na.rm=TRUE)
cv

#Medidas de Posição
#quantis, percentis e quartis
quantile(malaria_qty$qty.parasites, na.rm = TRUE)

#percentis específicos
quantile(malaria_qty$qty.parasites, probs = c(0.10, 0.25, 0.5, 0.75, 0.90), na.rm = TRUE)

#Medidas de Forma
#Assimetria (Skewness)
skewness(malaria_qty$qty.parasites, na.rm = TRUE)

#Curtose
kurtosis(malaria_qty$qty.parasites, na.rm = TRUE)

#Gráficos
#histograma
ggplot(malaria_qty, aes(x = qty.parasites)) +
  geom_histogram(bins = 30, fill="steelblue")

#boxplot(outliers e posição)
ggplot(malaria_qty, aes(y = qty.parasites)) +
  geom_boxplot(fill="tomato")

#densidade
ggplot(malaria_qty, aes(x = qty.parasites)) +
  geom_density(fill="blue", alpha=0.3)

```